apiVersion: apps/v1
kind: Deployment
metadata:
  name: rxnorm-api
  namespace: py-api
  labels:
    app: rxnorm-api
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rxnorm-api
  template:
    metadata:
      labels:
        app: rxnorm-api
        env: dev
    spec:
      containers:
      - name: rxnorm-api
        image: index.docker.io/chaitanyavatte/renal:rxnorm
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP