apiVersion: v1
kind: Service
metadata:
  name: rxnorm-api
  namespace: py-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app:  rxnorm-api
  ports:
  - protocol: "TCP"
    port:  5001
    targetPort: 5000
  type:  LoadBalancer
